<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Net4x.Xamarin.Forms.Xaml</PackageId>
    <Description>XAML loader and markup support for Xamarin.Forms.</Description>
    <IsPackable>true</IsPackable>

    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xamarin.Forms.Core\Xamarin.Forms.Core.csproj">
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Diagnostics\" />
  </ItemGroup>
</Project>
