<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Net4x.Xamarin.Forms.Platform</PackageId>
    <Description>Platform facade referenced by the Xamarin.Forms renderers.</Description>
    <IsPackable>true</IsPackable>

    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
  </PropertyGroup>
</Project>