<Project>
  <Import Project="..\Xamarin.Forms.Build.Tasks\build\Xamarin.Forms.Debug.targets" Condition="'$(BuildingInsideVisualStudio)' == 'true' AND Exists('$(__XFBuildTasksLocation)Xamarin.Forms.Build.Tasks.dll')" />
  <Import Project="..\Xamarin.Forms.Build.Tasks\build\Xamarin.Forms.Debug.targets" Condition="'$(BuildingInsideVisualStudio)' != 'true'" />
</Project>
